baseURL = "http://www.nmcconnell.com/"
title = "Nathanial L. McConnell"
author = "Nathanial L. McConnell"
theme = "skelethorn"

# General configuration
config = "config.toml"
source = ""
archetypeDir = "archetype"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"
staticDir = "static"
defaultExtension = "html"
defaultLayout = "post"
disablePathToLower = false
hasCJKLanguage = false

googleAnalytics = "UA-75154327-1"
disqus = "nmcconnellcom"
# CSS name for highlight.js
highlightjs = "androidstudio"
languageCode = "en-us"
dateFormat = "02 Jan 2006, 15:04"
footnoteAnchorPrefix = ""
footnoteReturnLinkContents = ""
toc = false # set to true for table of contents in all content

buildDrafts = false
buildFuture = false
MetaDataFormat = "toml"
canonifyURLs = true
relativeURLs = false
uglyURLs = false
watch = true
disableLiveReload = false
disableRSS = false
disableSitemap = false
noTimes = false
paginate = 10
paginatePath = "page"
pluralizeListtitles = true
preserveTaxonomyNames = false
pygmentsStyle = "monokai"
pygmentsStyleUseClasses = true
syntaxHighlightTheme = "solarized_dark.min.css"
sitemap = ""
stepAnalysis = false
verbose = true
verboseLog = true

ignoreFiles = []

editor = "atom"
newContentEditor = "atom"
log = true
logFile = "log.json"

[permalinks]
  announcements = "/:section/:year/:month/:slug"
  assignments = "/:section/:year/:month/:slug"
  lessons = "/:section/:year/:month/:slug"
  posts = "/:section/:year/:month/:slug"
  quotes = "/:section/:year/:month/:filename"

# Shown in the side menu
copyright = "&copy; 2016. All rights reserved."

[taxonomies]
  tag = "tags"
  topic = "topics"
  course = "courses"
  series = "series"

[params]
  # Shown in the home page
  subtitle = "Braindumps, Diatribes, & Other Distractions"
  brand = "nmcconnell"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Announcements"
    pre = "<i class='fa fa-bullhorn fa-fw'></i>"
    weight = 1
    identifier = "announcement"
    url = "/announcement/"
  [[menu.main]]
    name = "Assignments"
    pre = "<i class='fa fa-code fa-fw'></i>"
    weight = 1
    identifier = "assignment"
    url = "/assignment/"
  [[menu.main]]
    name = "Lessons"
    pre = "<i class='fa fa-graduation-cap fa-fw'></i>"
    weight = 1
    identifier = "lesson"
    url = "/lesson/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Quotes"
    pre = "<i class='fa fa-quote-left fa-fw'></i>"
    weight = 1
    identifier = "quote"
    url = "/quote/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 3
    url = "/contact/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "FluxAugur"
  facebook = "FluxAugur"
  googleplus = "NathanialMcConnell"
  tumblr = "fluxaugur"

  # SNS audio/music sharing
  lastfm = "FluxAugur"
  spotify = "121088690"

  # SNS photo/video sharing
  instagram = "FluxAugur"
  flickr = "fluxaugur"
  pinterest = "fluxaugur"
  youtube = "FluxAugur"
  vimeo = "fluxaugur"
  slideshare = "NathanialMcConnell"

  # SNS career oriented
  linkedin = "nathanialmcconnell"
  namedrop = "nathanialmcconnell"
  trello = "nathaniallmcconnell"
  skype = "fluxaugur"

  # SNS gaming
  boardgamegeek = "FluxAugur"
  steam = "fluxaugur"

  # SNS news
  reddit = "FluxAugur"
  hackernews = "FluxAugur"

  # SNS Travel
  foursquare = "fluxaugur"

  # SNS Techie
  github = "FluxAugur"
  bitbucket = "FluxAugur"
  stackoverflow = "2199507"
  pastebin = "FluxAugur"
  keybase = "fluxaugur"

  # SNS Payments
  flattr = "vkq1on"
  bitcoin = "fluxaugur"
  paypal = "fluxaugur"
